JobPortalWeb/Controllers/JobsDefinitionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobPortalWeb.Data;
using Microsoft.AspNet.Identity;

namespace JobPortalWeb.Controllers
{
    public class JobsDefinitionsController : Controller
    {
        private EmploymentGateEntities db = new EmploymentGateEntities();

        // GET: JobsDefinitions
        public ActionResult Index(string  SearchPhrase ="" )
        {
            var jobsDefinitions = db.JobsDefinitions.Include(j => j.Degree);
            var result = jobsDefinitions.Where(p => p.JobTitle.ToLower().Contains(SearchPhrase.ToLower()) || p.JobDescription.ToLower().Contains(SearchPhrase.ToLower()) ||  SearchPhrase.Trim() == ""  ).ToList();
            ViewBag.searchPhrase = SearchPhrase;
            return View(result);
        }

        // GET: JobsDefinitions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobsDefinition jobsDefinition = db.JobsDefinitions.Find(id);
            if (jobsDefinition == null)
            {
                return HttpNotFound();
            }
            return View(jobsDefinition);
        }

        // GET: JobsDefinitions/Create
        public ActionResult Create()
        {
            ViewBag.MinDegreeId = new SelectList(db.Degrees, "Id", "Value");
            return View();
        }

        // POST: JobsDefinitions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,JobTitle,JobDescription,StartPublishDate,EndPublishDate,MinDegreeId,Major,MinYearsOfExperance,JobRequirement,IsActive")] JobsDefinition jobsDefinition)
        {
            if (ModelState.IsValid)
            {
                db.JobsDefinitions.Add(jobsDefinition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MinDegreeId = new SelectList(db.Degrees, "Id", "Value", jobsDefinition.MinDegreeId);
            return View(jobsDefinition);
        }

        // GET: JobsDefinitions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobsDefinition jobsDefinition = db.JobsDefinitions.Find(id);
            if (jobsDefinition == null)
            {
                return HttpNotFound();
            }
            ViewBag.MinDegreeId = new SelectList(db.Degrees, "Id", "Value", jobsDefinition.MinDegreeId);
            return View(jobsDefinition);
        }
        
        // GET: JobsDefinitions/Edit/5
        [Authorize]
        public ActionResult ApplyToJob(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobsDefinition jobsDefinition = db.JobsDefinitions.Find(id);
            if (jobsDefinition == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();
            var profileInfo = db.Profiles.Where(p => p.UserId == userId).Include("CvJobs").Include("CVEducations").Include("CVSkills").FirstOrDefault();
            if (!db.JobApplications.Any(p=>p.JobId == id && p.ApplicantProfileId == profileInfo.Id))
            {
                JobApplication entity = new JobApplication();
                entity.JobId = id.Value;
                entity.ApplicantProfileId = profileInfo.Id;
                entity.ApplicationDate = DateTime.Now; 
                db.JobApplications.Add(entity);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "JobApplications");
        }

        // POST: JobsDefinitions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,JobTitle,JobDescription,StartPublishDate,EndPublishDate,MinDegreeId,Major,MinYearsOfExperance,JobRequirement,IsActive")] JobsDefinition jobsDefinition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobsDefinition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MinDegreeId = new SelectList(db.Degrees, "Id", "Value", jobsDefinition.MinDegreeId);
            return View(jobsDefinition);
        }

        // GET: JobsDefinitions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobsDefinition jobsDefinition = db.JobsDefinitions.Find(id);
            if (jobsDefinition == null)
            {
                return HttpNotFound();
            }
            return View(jobsDefinition);
        }

        // POST: JobsDefinitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            JobsDefinition jobsDefinition = db.JobsDefinitions.Find(id);
            db.JobsDefinitions.Remove(jobsDefinition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobPortalWeb/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/Content/css/Account.css" rel="stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Job Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <section class="login-section">
        <div class="login-container">
            <div class="login-form">
                @RenderBody()
            </div>
            <div class="login-picture"></div>

        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>

@Html.Partial("_PartialFooter")
</html>

JobPortalWeb/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/css/Home.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <img src="~/Content/images/jobportallogo.png" class="login-logo" style=" width: 2em; margin: 7px; border-radius: 3px; margin-left: 2em;" />
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("Job Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav header-links">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Jobs List", "Index", "JobsDefinitions")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="body-content">
        @RenderBody() 
      @Html.Partial("_PartialFooter")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

JobPortalWeb/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
@Html.Partial("_PartialFooter")
</html>

JobPortalWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/css/sidemenu.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>


<body>

    <section class="main-section">
        <div class="main-app-container">
            <div class="side-menu-container">
                <div class="side-menu-subcontainer">
                    <div class="sidemenu-header">
                        <img src="~/Content/images/jobportallogo.png" class="login-logo" />
                        @*<img src="Src/Imgs/logo.png" class="menu-logo" alt="">*@
                    </div>
                    <div class="submenu-items">
                        <ul class="sidemenu-list">
                            <li class="nav-menu-item" data-linkref="Home/index">
                                <a href="~/Home/Index">
                                    <span class="icon"><i class="fas fa-home"></i></span>
                                    <span class="item-title">Home</span>
                                </a>
                            </li>
                            <li class="nav-menu-item" data-linkref="JobsDefinitions">
                                <a href="~/JobsDefinitions/Index">
                                    <span class="icon"><i class="fas fa-th-list"></i></span>
                                    <span class="item-title">Job Listing</span>
                                </a>
                            </li>
                            <li class="nav-menu-item" data-linkref="JobApplications">
                                <a href="~/JobApplications/index">
                                    <span class="icon"><i class="fab fa-wpforms"></i></span>
                                    <span class="item-title">My Applications</span>
                                </a>
                            </li>
                            <li class="nav-menu-item" data-linkref="CvJobs">
                                <a href="~/CvJobs/index">
                                    <span class="icon"><i class="fas fa-file-invoice"></i></span>
                                    <span class="item-title">CV Builder</span>
                                </a>
                            </li> 
                            <li class="nav-menu-item" data-linkref="CVViewer">
                                <a href="~/Profiles/CVViewer">
                                    <span class="icon"><i class="fas fa-file-contract"></i></span>
                                    <span class="item-title">CV Viewer</span>
                                </a>
                            </li>
                            <li class="nav-menu-item" data-linkref="Profiles">
                                <a href="~/Profiles/Edit">
                                    <span class="icon"><i class="far fa-id-card"></i></span>
                                    <span class="item-title">My Profile</span>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>

            </div>
            <div class="content-container">
                <div class="application-header">
                    <span> @ViewBag.Title</span>
                    <div class="login-profile-info">
                        @*<img src="" alt="">*@
                        <div class="welcome-container"><span> @Html.Partial("_LoginPartial")</span> </div>
                    </div>
                </div>
                <div class="applicaion-content">
                    @RenderBody()
                </div>
            </div>
        </div>
    </section>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
        document.querySelectorAll(".nav-menu-item").forEach(function (item) {
            item.addEventListener("click", function () {
                document.querySelectorAll(".nav-menu-item").forEach(function (innerItem) {

                    //innerItem.classList.remove("active");
                });
                //this.classList.add("active");
            });
        });
        selectLink();

        function selectLink() {
            const collection = document.querySelectorAll(".nav-menu-item");

            collection.forEach(element => {
                let subUrl = element.dataset.linkref;
                if (window.location.href.indexOf(subUrl) > 0) {
                    element.classList.add("active");
                }
               
            });
        }
         
        
    </script>
</body>
@Html.Partial("_PartialFooter")
</html>

JobPortalWeb/Views/Shared/_PartialFooter.cshtml
<link href="~/Content/css/footer.css" rel="stylesheet" />
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="~/Home/About">About Us</a></li>
                        <li><a href="~/JobsDefinitions/Index">Job List</a></li>
                        <li><a href="~/Home/Contact">Contact Us</a></li>
                        
                    </ul>
                </div>
                
                <div class="col-lg-4 col-md-4 footer-contact">
                    <h4>Contact Us</h4>
                    <p> A108 Adam Street <br /> Jordan, NY 535022<br />Amman <br /><br /> <strong>Phone:</strong> 0777777777<br /> <strong>Email:</strong> jobPortal@gmail.com<br /> </p>
                </div>
                <div class="col-lg-4 col-md-4 footer-info">
                    <h3>ABOUT US</h3>
                    <p>Our culture is our foundation, and we take great pride in it. It’s the collective personality of our organization. It sets us apart, defines who we are, and shapes what we aspire to be.</p>
                    <div class="social-links mt-3"> <a href="https://twitter.com/" class="twitter"><i class="fab fa-twitter"></i></a> <a href="https://www.facebook.com/" class="facebook"><i class="fab fa-facebook"></i></a> <a href="https://www.instagram.com/" class="instagram"><i class="fab fa-instagram"></i></a> <a href="https://www.linkedin.com/feed/" class="linkedin"><i class="fab fa-linkedin"></i></a> </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright"> © Copyright <strong><span>JobPortal</span></strong>. All Rights Reserved </div>
    </div>
</footer>